export const PET_MAIN_LOOP_INTERVAL_MS = 16
export const IDLE_TIMEOUT_MS = 10000

export const REACTION_SURPRISED_PRIORITY = 100
export const REACTION_SLEEPY_PRIORITY = 10
export const REACTION_IDLE_PRIORITY = 0

export const REACTION_SURPRISED_DURATION_MS = 1500
export const REACTION_SLEEPY_DURATION_MS = 3000
export const REACTION_IDLE_DURATION_MS = 0

export const HAPPY_SOUND_VOLUME = 0.35
export const HAPPY_SOUND_FIRST_HZ = 880
export const HAPPY_SOUND_SECOND_HZ = 1175
export const HAPPY_SOUND_DURATION_MS = 80

export const HAPPY_MOTION_YAW = 0.12
export const HAPPY_MOTION_STEP_SECONDS = 0.15

export const PET_SWIPE_MIN_DISTANCE_Y = 60
export const PET_SWIPE_MAX_DRIFT_X = 45
export const PET_SWIPE_MIN_VERTICAL_DOMINANCE = 1.5
export const PET_SWIPE_MAX_DURATION_TICKS = 1500
export const PET_SWIPE_START_MAX_Y = 140
