export const PET_MAIN_LOOP_INTERVAL_MS = 16
export const IDLE_TIMEOUT_MS = 10000

export const REACTION_SURPRISED_PRIORITY = 100
export const REACTION_SLEEPY_PRIORITY = 10
export const REACTION_IDLE_PRIORITY = 0

export const REACTION_SURPRISED_DURATION_MS = 1500
export const REACTION_SLEEPY_DURATION_MS = 3000
export const REACTION_IDLE_DURATION_MS = 0

export const SURPRISED_SOUND_VOLUME = 0.35
export const SURPRISED_SOUND_HZ = 1175
export const SURPRISED_SOUND_DURATION_MS = 80

export const SLEEPY_MOTION_PITCH = 0.08
export const SLEEPY_MOTION_STEP_SECONDS = 0.35

export const PET_SWIPE_MIN_DISTANCE_Y = 60
export const PET_SWIPE_MAX_DRIFT_X = 45
export const PET_SWIPE_MIN_VERTICAL_DOMINANCE = 1.5
export const PET_SWIPE_MAX_DURATION_TICKS = 1500
export const PET_SWIPE_START_MAX_Y = 140
